# Generated by Django 2.2.5 on 2021-06-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datetoevent',
            fields=[
                ('date', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('event1', models.CharField(blank=True, max_length=45, null=True)),
                ('event2', models.CharField(blank=True, max_length=45, null=True)),
                ('event3', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'datetoevent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eventtodate',
            fields=[
                ('event', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('eventdate', models.CharField(blank=True, db_column='eventDate', max_length=50, null=True)),
            ],
            options={
                'db_table': 'eventtodate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Officeinfo',
            fields=[
                ('officename', models.CharField(db_column='officeName', max_length=50, primary_key=True, serialize=False)),
                ('officetel', models.CharField(blank=True, db_column='officeTel', max_length=50, null=True)),
                ('officelocation', models.CharField(blank=True, db_column='officeLocation', max_length=50, null=True)),
            ],
            options={
                'db_table': 'officeinfo',
                'managed': False,
            },
        ),
    ]
